# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(799, 493)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 801, 491))
        self.frame.setStyleSheet("QFrame{\n"
"    color: rgb(220, 220, 220);\n"
"    \n"
"    background-color: rgb(39, 38, 53);\n"
"    border-radius:8px;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.bt_send = QtWidgets.QPushButton(self.frame)
        self.bt_send.setGeometry(QtCore.QRect(690, 440, 101, 41))
        self.bt_send.setStyleSheet("background-color: rgb(75, 73, 102);\n"
"color: rgb(220, 220, 220);\n"
"border-style:none;\n"
"border-radius: 8px;\n"
"text-align: center;")
        self.bt_send.setObjectName("bt_send")
        self.textEdit_message = QtWidgets.QPlainTextEdit(self.frame)
        self.textEdit_message.setGeometry(QtCore.QRect(10, 440, 671, 41))
        self.textEdit_message.setToolTip("")
        self.textEdit_message.setToolTipDuration(-1)
        self.textEdit_message.setAccessibleDescription("")
        self.textEdit_message.setAutoFillBackground(False)
        self.textEdit_message.setStyleSheet("background-color: rgb(75, 73, 102);\n"
"color:rgb(200,200,200);\n"
"border-style:none;\n"
"border-radius: 8px;")
        self.textEdit_message.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_message.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.textEdit_message.setTabStopWidth(50)
        self.textEdit_message.setCenterOnScroll(False)
        self.textEdit_message.setObjectName("textEdit_message")
        self.listView_messages = QtWidgets.QListView(self.frame)
        self.listView_messages.setGeometry(QtCore.QRect(10, 10, 781, 421))
        self.listView_messages.setStyleSheet("background-color: rgb(75, 73, 102);\n"
"color:rgb(200,200,200);\n"
"border-style:none;\n"
"border-radius: 8px;")
        self.listView_messages.setDefaultDropAction(QtCore.Qt.IgnoreAction)
        self.listView_messages.setObjectName("listView_messages")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.bt_send.setText(_translate("MainWindow", "Send"))
        self.textEdit_message.setPlaceholderText(_translate("MainWindow", "message"))
