# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SplashUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SplashScreen(object):
    def setupUi(self, SplashScreen):
        SplashScreen.setObjectName("SplashScreen")
        SplashScreen.resize(680, 400)
        self.centralwidget = QtWidgets.QWidget(SplashScreen)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.dropShadowFrame = QtWidgets.QFrame(self.centralwidget)
        self.dropShadowFrame.setStyleSheet("QFrame {    \n"
"    background-color: rgb(56, 58, 89);    \n"
"    color: rgb(220, 220, 220);\n"
"    border-radius: 10px;\n"
"}")
        self.dropShadowFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.dropShadowFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.dropShadowFrame.setObjectName("dropShadowFrame")
        self.label_title = QtWidgets.QLabel(self.dropShadowFrame)
        self.label_title.setGeometry(QtCore.QRect(0, 63, 661, 71))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(60)
        self.label_title.setFont(font)
        self.label_title.setStyleSheet("color: rgb(39, 195, 230);")
        self.label_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_title.setObjectName("label_title")
        self.label_description = QtWidgets.QLabel(self.dropShadowFrame)
        self.label_description.setGeometry(QtCore.QRect(0, 150, 661, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.label_description.setFont(font)
        self.label_description.setStyleSheet("color: rgb(98, 114, 164);")
        self.label_description.setAlignment(QtCore.Qt.AlignCenter)
        self.label_description.setObjectName("label_description")
        self.progressBar = QtWidgets.QProgressBar(self.dropShadowFrame)
        self.progressBar.setGeometry(QtCore.QRect(50, 280, 561, 23))
        self.progressBar.setStyleSheet("QProgressBar{\n"
"    background-color: rgb(75, 73, 102);\n"
"    color:rgb(200,200,200);\n"
"    border-style:none;\n"
"    border-radius: 8px;\n"
"    text-align: center;\n"
"}\n"
"\n"
"QProgressBar::chunk{\n"
"border-radius:8px;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(29, 144, 170, 255), stop:1 rgba(20, 98, 116, 255));\n"
"}")
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.label_loading = QtWidgets.QLabel(self.dropShadowFrame)
        self.label_loading.setGeometry(QtCore.QRect(0, 310, 661, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.label_loading.setFont(font)
        self.label_loading.setStyleSheet("color: rgb(98, 114, 164);")
        self.label_loading.setAlignment(QtCore.Qt.AlignCenter)
        self.label_loading.setObjectName("label_loading")
        self.label_credits = QtWidgets.QLabel(self.dropShadowFrame)
        self.label_credits.setGeometry(QtCore.QRect(20, 350, 621, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_credits.setFont(font)
        self.label_credits.setStyleSheet("color: rgb(98, 114, 164);")
        self.label_credits.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_credits.setObjectName("label_credits")
        self.plainTextEdit_nick = QtWidgets.QPlainTextEdit(self.dropShadowFrame)
        self.plainTextEdit_nick.setGeometry(QtCore.QRect(190, 220, 211, 23))
        self.plainTextEdit_nick.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.plainTextEdit_nick.setStyleSheet("background-color: rgb(75, 73, 102);\n"
"padding-left:8;")
        self.plainTextEdit_nick.setInputMethodHints(QtCore.Qt.ImhNone)
        self.plainTextEdit_nick.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.plainTextEdit_nick.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.plainTextEdit_nick.setObjectName("plainTextEdit_nick")
        self.pushButton_connect = QtWidgets.QPushButton(self.dropShadowFrame)
        self.pushButton_connect.setGeometry(QtCore.QRect(410, 220, 71, 23))
        self.pushButton_connect.setStyleSheet("background-color: rgb(98, 114, 164);\n"
"color:rgb(39, 195, 230);\n"
"border-style:none;\n"
"border-radius: 8px;\n"
"text-align: center;")
        self.pushButton_connect.setObjectName("pushButton_connect")
        self.label_error = QtWidgets.QLabel(self.dropShadowFrame)
        self.label_error.setGeometry(QtCore.QRect(0, 250, 658, 20))
        self.label_error.setStyleSheet("color: rgb(255, 86, 71);")
        self.label_error.setAlignment(QtCore.Qt.AlignCenter)
        self.label_error.setObjectName("label_error")
        self.pushButton_exit = QtWidgets.QPushButton(self.dropShadowFrame)
        self.pushButton_exit.setGeometry(QtCore.QRect(610, 10, 32, 23))
        self.pushButton_exit.setStyleSheet("background-color: rgb(75, 73, 102);\n"
"color: rgb(39, 195, 230);\n"
"border-style:none;\n"
"border-radius: 8px;\n"
"text-align: center;")
        self.pushButton_exit.setObjectName("pushButton_exit")
        self.verticalLayout.addWidget(self.dropShadowFrame)
        SplashScreen.setCentralWidget(self.centralwidget)

        self.retranslateUi(SplashScreen)
        QtCore.QMetaObject.connectSlotsByName(SplashScreen)

    def retranslateUi(self, SplashScreen):
        _translate = QtCore.QCoreApplication.translate
        SplashScreen.setWindowTitle(_translate("SplashScreen", "MainWindow"))
        self.label_title.setText(_translate("SplashScreen", "TCP CHAT"))
        self.label_description.setText(_translate("SplashScreen", "Chat application over local tcp "))
        self.label_loading.setText(_translate("SplashScreen", "loading..."))
        self.label_credits.setText(_translate("SplashScreen", "Created by Rejfin"))
        self.plainTextEdit_nick.setPlaceholderText(_translate("SplashScreen", "Nick"))
        self.pushButton_connect.setText(_translate("SplashScreen", "Connect"))
        self.label_error.setText(_translate("SplashScreen", "TextLabel"))
        self.pushButton_exit.setText(_translate("SplashScreen", "X"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SplashScreen = QtWidgets.QMainWindow()
    ui = Ui_SplashScreen()
    ui.setupUi(SplashScreen)
    SplashScreen.show()
    sys.exit(app.exec_())
